[package]
name = "kstring"
version = "1.0.4"
authors = ["Ed Page <eopage@gmail.com>"]
description = "Key String: optimized for map keys"
keywords = ["serde", "serialization", "string"]
categories = ["data-structures", "text-processing"]
repository = "https://github.com/cobalt-org/kstring"
documentation = "https://docs.rs/kstring"
readme = "README.md"
license = "MIT OR Apache-2.0"
edition = "2018"

[badges]
azure-devops = { project = "cobalt-org", pipeline = "kstring" }
maintenance = { status = "passively-maintained" }

[features]
default = ["serde"]

[dependencies]
serde = { version = "1.0", optional = true }

[dev-dependencies]
criterion = "0.3"
smol_str = "0.1.18"

[[bench]]
name = "clone"
harness = false

[[bench]]
name = "access"
harness = false
